name: Publish
on:
  workflow_run:
    workflows: [ "Integrate" ]
    types: [ completed ]
  push:
    branches: [ 'release/v[0-9].[0-9].[0-9]' ]
jobs:
  pypi:
    name: Publish to PyPI
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pySunshower
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install Python dependencies
        run: pipx install poetry
      - name: Build the artifact
        run: poetry build
      - name: Publish the artifact
        uses: pypa/gh-action-pypi-publish@release/v1
